"""
reporter.py — Report Assembly + Output
=========================================
Technology: rich (terminal), pathlib (file), json (sidecar)

Why Markdown as the primary output format:
  Markdown is universally renderable — GitHub, Notion, VS Code, Obsidian,
  and the River's Engineer UI all consume it natively. It can be version-
  controlled, diffed, and searched with grep. It requires zero dependencies
  to read. It's the right format for documentation that developers will
  actually use.

Why a JSON sidecar:
  The UI needs structured data, not a blob of markdown. The JSON sidecar
  is written alongside the .md file and contains the same information in
  a structured format the UI can parse for its visual components (node graphs,
  verdict panels, branch selectors, etc.).

Why rich for terminal output:
  rich handles ANSI colors across Mac/Linux/Windows (including Windows Terminal
  and VS Code integrated terminal). It renders markdown headers and code blocks
  in the terminal, giving developers a preview without opening a file.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.text import Text


def generate(
    archaeology: str,
    critique: str,
    analysis: Dict[str, Any],
    output_path: Optional[Path],
    project_path: Path,
) -> Path:
    """
    Assemble the full book from both LLM outputs, save as .md + .json sidecar.

    Args:
        archaeology:   The Archaeologist's response (Chapters 1-4)
        critique:      The Critic's response (Chapter 5 + Reverse Path)
        analysis:      The structured analysis dict (for metadata)
        output_path:   User-specified output path, or None for auto-generation
        project_path:  The analyzed project's path (for relative naming)

    Returns:
        Path to the saved .md file
    """
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    project_name = analysis.get("project_name", "unknown")

    # Determine output path
    if output_path:
        md_path = Path(output_path).with_suffix(".md")
    else:
        md_path = project_path.resolve() / f"river-report-{timestamp}.md"

    json_path = md_path.with_suffix(".json")

    # Assemble full markdown document
    full_report = _assemble_markdown(
        archaeology=archaeology,
        critique=critique,
        analysis=analysis,
        timestamp=timestamp,
    )

    # Write markdown
    md_path.write_text(full_report, encoding="utf-8")

    # Write JSON sidecar
    sidecar = _build_sidecar(
        archaeology=archaeology,
        critique=critique,
        analysis=analysis,
        timestamp=timestamp,
    )
    json_path.write_text(json.dumps(sidecar, indent=2), encoding="utf-8")

    return md_path


def _assemble_markdown(
    archaeology: str,
    critique: str,
    analysis: Dict[str, Any],
    timestamp: str,
) -> str:
    """
    Combine all pieces into the final markdown document.
    """
    project_name = analysis.get("project_name", "Unknown Project")
    primary_language = analysis.get("primary_language", "Unknown")
    file_count = analysis.get("file_count", 0)
    frameworks = ", ".join(analysis.get("frameworks", [])) or "None detected"
    branch = analysis.get("branch")
    date_str = datetime.now().strftime("%B %d, %Y at %H:%M")

    branch_note = f" | Branch: `{branch}`" if branch else ""
    dep_count = sum(
        len(deps)
        for deps in analysis.get("dependencies", {}).values()
    )

    header = f"""---
generated_by: River's Engineer v0.1.0
project: {project_name}
analyzed: {date_str}
---

# River's Engineer Report: {project_name}

> **Analyzed**: {date_str}{branch_note}
> **Files**: {file_count} | **Language**: {primary_language} | **Frameworks**: {frameworks} | **Dependencies**: {dep_count}

---

*This report was generated by two collaborating LLMs:*
- *🏺 **The Archaeologist** — read the codebase and produced Chapters 1–4*
- *⚔️  **The Critic** — challenged the findings and produced Chapter 5 + the Reverse Path*

---

"""

    footer = f"""

---

*Generated by [River's Engineer](https://github.com/yourusername/rivers-engineer) — `pip install rivers-engineer`*
*Run `river ui` to view this report as an interactive visual diagram.*
"""

    return header + archaeology + "\n\n---\n\n" + critique + footer


def _build_sidecar(
    archaeology: str,
    critique: str,
    analysis: Dict[str, Any],
    timestamp: str,
) -> Dict[str, Any]:
    """
    Build the JSON sidecar file that the UI reads.
    Contains structured metadata + the full text of each section.
    """
    return {
        "version": "0.1.0",
        "generated_at": timestamp,
        "project": {
            "name": analysis.get("project_name"),
            "path": analysis.get("root_path"),
            "branch": analysis.get("branch"),
            "primary_language": analysis.get("primary_language"),
            "languages": analysis.get("languages", []),
            "frameworks": analysis.get("frameworks", []),
            "file_count": analysis.get("file_count", 0),
            "total_lines": analysis.get("total_lines", 0),
            "entry_points": analysis.get("entry_points", []),
        },
        "dependencies": analysis.get("dependencies", {}),
        "file_tree": analysis.get("file_tree", ""),
        "book": {
            "archaeology": archaeology,
            "critique": critique,
        },
        "ui_hints": {
            "layers": _extract_layers(archaeology),
            "verdict_items": _extract_verdict_items(critique),
        },
    }


def _extract_layers(archaeology: str) -> list:
    """
    Parse chapter headings from the archaeology text to produce
    a list of layer names for the UI's architecture flow diagram.
    """
    layers = []
    for line in archaeology.splitlines():
        if line.startswith("## Chapter"):
            # "## Chapter 1: The Entry Point" → "The Entry Point"
            parts = line.replace("## Chapter", "").strip().split(":", 1)
            if len(parts) == 2:
                layers.append({
                    "number": parts[0].strip(),
                    "name": parts[1].strip(),
                })
    return layers


def _extract_verdict_items(critique: str) -> Dict[str, list]:
    """
    Parse the Tech Verdict section to extract strong/redundant/replace items.
    """
    verdict = {
        "strong": [],
        "redundant": [],
        "replace": [],
    }

    current_section = None
    for line in critique.splitlines():
        line_lower = line.lower()
        if "what's strong" in line_lower or "✅" in line:
            current_section = "strong"
        elif "what's redundant" in line_lower or "⚠️" in line:
            current_section = "redundant"
        elif "should be replaced" in line_lower or "🔴" in line:
            current_section = "replace"
        elif "business layer" in line_lower or "💼" in line:
            current_section = None
        elif current_section and line.strip().startswith("**") and "**" in line[2:]:
            # Extract bolded items like **Django** or **Current**: Redis
            import re
            matches = re.findall(r"\*\*([^*]+)\*\*", line)
            if matches:
                verdict[current_section].extend(matches)

    return verdict


def print_preview(report_path: Path, console: Console) -> None:
    """
    Print the first ~40 lines of the report to the terminal using rich's
    Markdown renderer. Gives the developer an immediate preview.
    """
    try:
        content = report_path.read_text(encoding="utf-8")
        # Show first chapter as preview
        lines = content.split("\n")
        preview_lines = []
        chapter_count = 0

        for line in lines:
            if line.startswith("## Chapter"):
                chapter_count += 1
                if chapter_count > 1:
                    preview_lines.append("\n*[...continued in full report...]*")
                    break
            preview_lines.append(line)
            if len(preview_lines) > 60:
                preview_lines.append("\n*[...continued in full report...]*")
                break

        preview_text = "\n".join(preview_lines)
        console.print(Markdown(preview_text))

    except Exception:
        console.print(f"[dim]Report saved to {report_path}[/dim]")
